### ISSUE TITLE
Should mention that ML-KEM is variable time

### ISSUE THREAD

**Issue by emanjon** [sfluhrer/ml-kem-security-considerations#17]
Should mention that ML-KEM is variable time. This is likely something readers would like to know. The variable time in ML-KEM does not affect Confidentiality but it can affect Availability.

**Comment by sfluhrer** [comment]
The only variable time part of ML-KEM I’m aware of is the SampleNTT subcomponent (actually, it could be made constant time by oversampling, but let’s talk about the straight-forward approach).

However, the time delta will be tiny; I haven’t run the numbers, but given that you do that sampling a large number of times, the total time taken should be close to a normal distribution, with a fairly small variance.  I don’t personally know if that’s worth mentioning.  Thoughts?

**Comment by emanjon** [comment]
Yes, I think I confused ML-KEM with ML-DSA very the delta is large. I agree that the total varience is probably low and therefore not worth mentioning
